[project]
name = "rss-ai-reporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.32",
    "flask==3.0.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
